name: Docs Build & Deploy
on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - package-lock.json
      - .github/workflows/docs.yml
  # Manual dispatch
  workflow_dispatch:
jobs:
  Build-And-Deploy:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          apt-get install -y git dirmngr gpg curl gawk
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.2 || true
          . $HOME/.asdf/asdf.sh
          asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git || true
          asdf install nodejs latest
          asdf local nodejs latest
          npm install --global yarn
          yarn install
          yarn docs:build
          rm -rf /home/james/Development/www/public/mzo-cli/*
          cp -r docs/.vuepress/dist/* /home/james/Development/www/public/mzo-cli
